### ISSUE TITLE
Can't update to 0.3.0 version

### ISSUE THREAD

**Issue by arvislacis** [SamVerschueren/vscode-final-newline#13]
Hello,

Thanks for creating this awesome and useful extension... Anyway, I have problems to upgrade extension to the latest version (0.3.0) from 0.2.0 in Visual Studio Code 1.5.3. VSC shows that update is available, I can install it (or it seems that update is installing) and after enabling update and restarting VSC, it shows that update is available again and in extension tab/menu it shows the 0.2.0 version next to your extension.

Don't know, maybe this bug is related to VSC not your extension.

**Comment by SamVerschueren** [comment]
You shouldn't be able to. `final-newline@0.3.0` uses the new API which is now in the Insiders Build and will be released with the next VS Code release in a couple of days. That version fixes #8 and #11. The reason you are seeing this update is due to a bug https://github.com/Microsoft/vscode/issues/13303 because `final-newline@0.3.0` is targetted to VS Code [^1.6.x](https://github.com/SamVerschueren/vscode-final-newline/blob/master/package.json#L7).
